name: updateRss

# easy to collect spam link, Temporarily pause
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    # comment
    name: "update audio"
    # comment
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions
        uses: actions/checkout@v1
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # - name: install packages
      #   run: "pip install --upgrade pip && pip install -r ./requirements.txt"
  
      - name: Update rss
        run: |
          # sudo apt update 
          sudo apt install git-lfs
          git lfs install
          # git clone https://huggingface.co/fishaudio/fish-speech-1.5 ./fish-speech-1.5
          git clone https://huggingface.co/2Noise/ChatTTS ./ChatTTS-model
          python -m pip install transformers==4.31.0
          python -m pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1
          sudo apt install libsox-dev ffmpeg 
          sudo apt install build-essential \
              cmake \
              libasound-dev \
              portaudio19-dev \
              libportaudio2 \
              libportaudiocpp0
          # git clone https://github.com/fishaudio/fish-speech
          # cd ./fish-speech
          # python -m pip install -e .[stable]
          # cd ..
          python -m pip install -q -U google-genai
          python -m pip install EbookLib beautifulsoup4 soundfile ChatTTS
          ls ./ChatTTS-model
          python -u ./entry_start.py ${{ secrets.GEMINI_API_KEY_NEWS_AUDIO }}
        timeout-minutes: 3600

      - name: Commit report
        env:
            GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.name 'wa008'
          git config --global user.email 'huzhipeng1024@outlook.com'
          git remote set-url origin https://wa008:${{ secrets.ACCESS_TOKEN }}@github.com/wa008/news-audio.git
          # git pull
          git checkout -b main
          git branch
          git add ./rss.xml
          git add ./the_economist/
          git commit -m "github workflows auto update rss"
          git push origin main
